services:
  loomi-api:
    container_name: loomi
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: loomi-postgres
    image: pgvector/pgvector:0.7.4-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  alembic:
    container_name: loomi-alembic
    build: .
    command: alembic upgrade head
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pgdata:
