"""v3_transforma_coluna_user_id_para_inteiro_na_tabela_chats

Revision ID: 0dc3fdc27355
Revises: cc34a4687626
Create Date: 2025-08-17 13:38:44.755069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc3fdc27355'
down_revision: Union[str, Sequence[str], None] = 'cc34a4687626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chats',
        'user_id',
        existing_type=sa.String(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="user_id::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###
