"""v2_atualiza_coluna_paint_name_e_adiciona_uploaded_by_para_tabela_paints

Revision ID: cc34a4687626
Revises: 1bb61d45e25b
Create Date: 2025-08-16 17:31:42.170014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc34a4687626'
down_revision: Union[str, Sequence[str], None] = '1bb61d45e25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paints', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('paints', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'paints', ['paint_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paints', type_='unique')
    op.drop_column('paints', 'updated_at')
    op.drop_column('paints', 'created_by')
    # ### end Alembic commands ###
