"""v4_atualiza_constraints_tabela_paints

Revision ID: d52199293df4
Revises: 0dc3fdc27355
Create Date: 2025-08-20 14:05:25.275341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52199293df4'
down_revision: Union[str, Sequence[str], None] = '0dc3fdc27355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('paints_paint_name_key'), 'paints', type_='unique')
    op.create_unique_constraint('uq_paint_name_color', 'paints', ['paint_name', 'color'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_paint_name_color', 'paints', type_='unique')
    op.create_unique_constraint(op.f('paints_paint_name_key'), 'paints', ['paint_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
